location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: true
      targetPort: 80
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--applicationinsights
        value: {{ .Env.APPLICATIONINSIGHTS_CONNECTION_STRING }}
  template:
    containers:
      - image: {{ .Image }}
        name: octopetsfe
        env:
          - name: ConnectionStrings__ApplicationInsights
            secretRef: connectionstrings--applicationinsights
          - name: REACT_APP_USE_MOCK_DATA
            value: "false"
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 5
      rules:
        - name: http-rule
          http:
            metadata:
              concurrentRequests: "100"
tags:
  azd-service-name: octopetsfe
  aspire-resource-name: octopetsfe
